### ISSUE TITLE
Not showing today but the date from the scope

### ISSUE THREAD

**Issue by toben** [g00fy-/angular-datepicker#197]
Hello,

I have a date-range with two date :

```html
<div date-range start="ar.startDate" end="ar.endDate" ></div>
```
These dates are filled after a $http request but for example, we are the 4 November and even if the startDate and endDate are in September, the date picker will show the month of 4 november. Is there a way to show the start month  and end month ?

Maybe, I missread the documentation...

Sorry for my english.

**Comment by DanTalash** [comment]
* As you mentioned, you receive the data via a `$http` request, meaning the directive initializes without the data being available. 
* I think the issue here is that the directive does not watch for data changes. Due to this deficiency, when your `$http` request returns the dates in question, the directive doesn't update the inner pickers and they remain on the default dates.
* I have fixed this issue and added a new PR.

**Comment by toben** [comment]
Ok ! Thank you very much. I wait the merge of your PR then
