### ISSUE TITLE
date-change on input field with date-time directive fails if the controller is bound with controllerAs

### ISSUE THREAD

**Issue by damoncasale** [g00fy-/angular-datepicker#211]
I've bound my controller for the view containing the input field with the date-time directive, with controllerAs="vm".  On the input field, date-change is defined as "vm.updateDate".  This fails to call the update function because the datePickerUtils.findFunction function is invalid for bound controller syntax.

I suggest this fix:

    findFunction: function (scope, name) {
      //Search scope ancestors for a matching function.
      //Can probably combine this and the below function
      //into a single search function and two comparison functions
      //Need to add support for lodash style selectors (eg, 'objectA.objectB.function')
      var parentScope = scope;
      var nameArray = name.split(".");
      do {
        parentScope = parentScope.$parent;
        if (angular.isFunction(parentScope[nameArray[0]])) {
          angular.forEach(nameArray, function(nameField, index) {
            parentScope = parentScope[nameField];
          });
          return parentScope;
        }
      } while (parentScope.$parent);

      return false;
    }

**Comment by DanTalash** [comment]
Hi, I took the liberty of rewriting your suggested fix, as there were some issues.

First, lets examine what is going on here. We're searching scopes for a function stored inside an object, such as:

```javascript
$scope.object = {
  someFunction: function() {}
}
```

To do this, we pass the string `'object.someFunction'` into the picker. The `findFunction` function splits it into an array, `['object', 'someFunction']`

However, in the following section of code, the logic doesn't make sense:

```javascript
    if (angular.isFunction(parentScope[nameArray[0]])) {
      angular.forEach(nameArray, function(nameField, index) {
        parentScope = parentScope[nameField];
      });
      return parentScope;
    }
```

In this example we are first checking if the current scope has a function named `object`, then iterating over each element in the `nameField` array and setting the `parentScope` object to a sub-object (`scope['object']`, then `scope['object']['someFunction']`). 

The problems with this approach are as follows:

1. We need to check that the last item in the list is a function, not the first. Otherwise, `$scope.object` cannot contain sub-objects if it is a function.
2. If the object does not contain some of the sub-keys, an exception will be thrown when trying to access properties of undefined.
3. The `parentScope` param is overwritten, meaning that we are not able to continue to the next scope in the ancestry chain, even if we realized that the current scope does not contain the data we want.
4. Only the `findFunction` function now accepts this syntax, whereas the `findParam` function does not.

### Solution

In order to resolve the above problems, I [rewrote your suggested solution](https://github.com/DanTalash/angular-datepicker/commit/8199ce2c3b3a61adfbd2bd1e48a92225ed493800). The two functions (`findFunction` and `findParam`) now use a third function, `scopeSearch`. This function will:

* Check to see if each sub-key exists.
* Does not overwrite the `parentScope` param, so that the search can continue if the current scope contains an object which only partially matches.
* Uses a comparison function passed from `findFunction` and `findParam` to determine if the final result is valid
  * The comparison function from `findFunction` requires the result to be a function.
  * The comparison function from `findParam` always returns true.

**Comment by damoncasale** [comment]
Looks great, thanks.  :)
