### ISSUE TITLE
user given input date changing to timezone

### ISSUE THREAD

**Issue by pavankumarkatakam** [g00fy-/angular-datepicker#213]
In some cases, i dont want to convert user given date time to timezone instead i want as it is date time given by the user. Is there any setting for this.

**Comment by christrude** [comment]
I seem to be having the same issue, my user in EST is choosing 00:00 but it's coming through as 05:00 for some reason.

**Comment by DanTalash** [comment]
If all you have is a timestamp and a timezone offset, this is not enough to unambiguously determine the timezone name. See [relevant stackoverflow question.](http://stackoverflow.com/questions/28374901/get-timezone-abbreviation-using-offset-value) You should get this info from the user, as using just the offset is inadequate.

You need the timezone name in order for moment-timezone to be able to set the correct timezone, as most timezone offsets contain multiple actual named timezones.

**Comment by pavankumarkatakam** [comment]
I dont understand your answer, what im asking is if user given input 06/10/2015 10:30:00 in the $scope value im getting the value 06/10/2015 04:00:00 (since my system tz is Asia\Calcutta (+5:30)), but iwan the user given input as it is what he has selected, that means in my $scope variable i want 06/10/2015 10:30:00. Is there any setting for this to work.

**Comment by DanTalash** [comment]
If you don't provide a timezone, then your machine local timezone will be used. However, everybody's local timezone may be different, so `12:00 UTC` will be shown as varying times in different time zones. If you want to show the same time to your other users as a specific user's selected date, then use their named timezone. 

For example, if a user is in the `Asia/Hong_Kong` timezone, their offset is `+8:00`. However, just because their offset is `+8:00` does not mean they are in the `Asia/Hong_Kong` timezone. Therefore, in order to reliably display times in the `Asia/Hong_Kong` timezone for everybody, just the offset is not enough (as this maps to multiple possible named time zones).

However, If all you want is to display times in a _specific_ timezone, (such as `UTC`) then just pass the name of the timezone you are interested in, and you don't need to worry about what timezone your users are in.

**Comment by pavankumarkatakam** [comment]
yeah, it cleared.
